{{- $name:= "postgres" }}

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $name }}
  namespace: {{ .Values.metadata.namespace }}
data:
    {{- range $k, $v :=  .Values.postgres.configMap }}
    {{ $k }}: {{ $v }}
    {{- end }}
