{{- $name:= "postgres" }}

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $name }}
  namespace: {{.Release.Namespace}}
data:
    {{- range $k, $v :=  .Values.postgres.configMap }}
    {{ $k }}: {{ $v }}
    {{- end }}
