{{- $name := "postgres" }}

kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ $name }}-pv-volume
  namespace: {{ .Values.metadata.namespace }}
  labels:
    type: local
    app: {{ $name }}

spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $name }}-pv-claim
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ $name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
