version: '3'
services:
  
  NGINX:
    image: nginx:latest
    depends_on:
      - pgadmin
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./logs/nginx:/var/log/nginx
    restart: always
    networks:
      - test

  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: testDB
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./PG_data/:/var/lib/postgresql/data
    restart: always
    networks:
      - test

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    links:
      - postgres:db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: testDB
      PGADMIN_DEFAULT_EMAIL: 'postgres@pg.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
    ports:
     - "5050:80"
    restart: always
    networks:
      - test
    

networks:
  test:
    external: true