version: '3'
services:
  
  NGINX:
    image: nginx:latest
    depends_on:
      - pgadmin
    ports:
      - 80:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./logs/nginx:/var/log/nginx
    restart: always
    networks:
      - test

  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: testDB
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./PG_data/:/var/lib/postgresql/data
    restart: always
    networks:
      - test

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    links:
      - postgres:db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: testDB
      PGADMIN_DEFAULT_EMAIL: 'postgres@pg.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
    ports:
     - "5050:80"
    restart: always
    networks:
      - test
    
  prometheus:
    depends_on:
      - postgres
    image: bitnami/prometheus
    volumes:
      - ./prometheus-config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    links:
      - postgres:db
    ports:
      - 9090:9090
    restart: always
    networks:
      - test
  
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://test:123456@postgres:5432/testDB?sslmode=disable"
    links:
      - postgres
      - prometheus
    networks:
      - test
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - test



networks:
  test:
    external: true