{{- $name:= "nginx" }}

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $name }}
  namespace: {{.Release.Namespace}}
data:
  proxy-connect-timeout: "10s"
  proxy-read-timeout: "10s"
  client-max-body-size: "2m"
  default.conf: {{ .Files.Get "location.conf" | quote }}